name: g4music # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.11' # just for humans, typically '1.2+git' or '1.3.2'
adopt-info: g4music

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
compression: lzo

slots:
  g4music:
    interface: dbus
    bus: session
    name: com.github.neithern.g4music

parts:
  g4music:
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/neithern/g4music.git
    source-tag: v${SNAPCRAFT_PROJECT_VERSION}
    meson-parameters:
      - --prefix=/snap/current/g4music/usr
    build-packages:
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0
    build-environment:
      - LDFLAGS: "-Wl,--copy-dt-needed-entries"
    organize:
      snap/current/g4music: .
    parse-info: [usr/share/metainfo/com.github.neithern.g4music.appdata.xml]
  cleanup:
    after:  # Make this part run last; list all your other parts here
      - g4music
    plugin: nil
    build-snaps:  # List all content-snaps and base snaps you're using here
      - gnome-42-2204
      - gtk-common-themes
      - core22
    override-prime: |
      set -eux
      for snap in "gnome-42-2204" "gtk-common-themes" "core22"; do
      cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done
      find $CRAFT_PRIME/usr/share/doc/ -type f -not -name 'copyright' -delete
apps:
  g4music:
    extensions: [gnome]
    command: usr/bin/g4music
    desktop: usr/share/applications/com.github.neithern.g4music.desktop
    common-id: com.github.neithern.g4music
    environment:
      GTK_USE_PORTAL: 1
    slots:
      - mpris
    plugs:
      - home
      - audio-playback
      - removable-media
      - mount-observe
